/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PrintId = IDL.Nat;
export const PrintFinish = IDL.Variant({
  'matte' : IDL.Null,
  'satin' : IDL.Null,
  'glossy' : IDL.Null,
});
export const PrintSize = IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat });
export const Product = IDL.Record({
  'printId' : PrintId,
  'finish' : PrintFinish,
  'productLabel' : IDL.Text,
  'price' : IDL.Nat,
  'printSize' : PrintSize,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PrintUpdate = IDL.Record({
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const AuthResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Print = IDL.Record({
  'id' : PrintId,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserInfo = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProfileResult = IDL.Variant({ 'ok' : UserInfo, 'err' : IDL.Text });
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPrint' : IDL.Func([PrintUpdate], [PrintId], []),
  'deleteMyAccount' : IDL.Func([IDL.Text], [AuthResult], []),
  'deletePrint' : IDL.Func([PrintId], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getActivePrints' : IDL.Func([], [IDL.Vec(Print)], ['query']),
  'getAllPrints' : IDL.Func([], [IDL.Vec(Print)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([IDL.Text], [ProfileResult], []),
  'getPrint' : IDL.Func([PrintId], [Print], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMyName' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'saveMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AuthResult],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'signIn' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'signOut' : IDL.Func([IDL.Text], [], []),
  'signUp' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePrint' : IDL.Func([PrintId, PrintUpdate], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'validateSession' : IDL.Func([IDL.Text], [AuthResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PrintId = IDL.Nat;
  const PrintFinish = IDL.Variant({
    'matte' : IDL.Null,
    'satin' : IDL.Null,
    'glossy' : IDL.Null,
  });
  const PrintSize = IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat });
  const Product = IDL.Record({
    'printId' : PrintId,
    'finish' : PrintFinish,
    'productLabel' : IDL.Text,
    'price' : IDL.Nat,
    'printSize' : PrintSize,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PrintUpdate = IDL.Record({
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const AuthResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Print = IDL.Record({
    'id' : PrintId,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserInfo = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProfileResult = IDL.Variant({ 'ok' : UserInfo, 'err' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPrint' : IDL.Func([PrintUpdate], [PrintId], []),
    'deleteMyAccount' : IDL.Func([IDL.Text], [AuthResult], []),
    'deletePrint' : IDL.Func([PrintId], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getActivePrints' : IDL.Func([], [IDL.Vec(Print)], ['query']),
    'getAllPrints' : IDL.Func([], [IDL.Vec(Print)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([IDL.Text], [ProfileResult], []),
    'getPrint' : IDL.Func([PrintId], [Print], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMyName' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'saveMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AuthResult],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'signIn' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'signOut' : IDL.Func([IDL.Text], [], []),
    'signUp' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePrint' : IDL.Func([PrintId, PrintUpdate], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'validateSession' : IDL.Func([IDL.Text], [AuthResult], []),
  });
};

export const init = ({ IDL }) => { return []; };