/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthResult = { 'ok' : string } |
  { 'err' : string };
export type ExternalBlob = Uint8Array;
export interface Print {
  'id' : PrintId,
  'title' : string,
  'active' : boolean,
  'description' : string,
  'image' : ExternalBlob,
}
export type PrintFinish = { 'matte' : null } |
  { 'satin' : null } |
  { 'glossy' : null };
export type PrintId = bigint;
export interface PrintSize { 'height' : bigint, 'width' : bigint }
export interface PrintUpdate {
  'title' : string,
  'active' : boolean,
  'description' : string,
  'image' : ExternalBlob,
}
export interface Product {
  'printId' : PrintId,
  'finish' : PrintFinish,
  'productLabel' : string,
  'price' : bigint,
  'printSize' : PrintSize,
}
export type ProfileResult = { 'ok' : UserInfo } |
  { 'err' : string };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserInfo { 'name' : string, 'email' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPrint' : ActorMethod<[PrintUpdate], PrintId>,
  'deleteMyAccount' : ActorMethod<[string], AuthResult>,
  'deletePrint' : ActorMethod<[PrintId], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getActivePrints' : ActorMethod<[], Array<Print>>,
  'getAllPrints' : ActorMethod<[], Array<Print>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProfile' : ActorMethod<[string], ProfileResult>,
  'getPrint' : ActorMethod<[PrintId], Print>,
  'getProduct' : ActorMethod<[string], Product>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMyName' : ActorMethod<[string, string], AuthResult>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'signIn' : ActorMethod<[string, string], AuthResult>,
  'signOut' : ActorMethod<[string], undefined>,
  'signUp' : ActorMethod<[string, string], AuthResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePrint' : ActorMethod<[PrintId, PrintUpdate], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'validateSession' : ActorMethod<[string], AuthResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];